version: "3.9"

services:
  prometheus_tst:
    image: prom/prometheus:latest
    container_name: prometheus_tst
    ports:
      - "9091:9090"   # Prometheus UI
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
    restart: unless-stopped

  node_exporter_tst:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter_tst
    ports:
      - "9101:9100"   # Node metrics
    command:
      - "--path.rootfs=/host"
    volumes:
      - "/:/host:ro"
    restart: unless-stopped

  grafana_tst:
    image: grafana/grafana:latest
    container_name: grafana_tst
    ports:
      - "3001:3000"  # Grafana UI
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped

  loki_tst:
    image: grafana/loki:2.9.4
    container_name: loki_tst
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./loki:/etc/loki
      - ./loki/data:/loki
    user: "0:0"
    restart: unless-stopped

  promtail_tst:
    image: grafana/promtail:2.9.4
    container_name: promtail_tst
    volumes:
      - ./promtail:/etc/promtail
      - ./backend/logs:/var/log/aoss   
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - loki_tst
    restart: unless-stopped
