apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: bfaxeqv2yuo74c
    access: proxy
    url: http://prometheus_tst:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    uid: loki_uid
    access: proxy
    url: http://loki_tst:3100
    editable: true
